import {
  Calendar,
  CreditCard,
  Github,
  HardDrive,
  Mail,
  MessageCircle,
  Slack,
  Triangle,
} from 'lucide-react';
import { translate, type Locale } from '@/lib/i18n';
import type { AtlasState } from './types';

// Seed data is generated relative to "now" so the product always
// opens in a believable, current state. All user-facing strings go
// through the locale dictionary — pass the locale to get a localized seed.

const DAY = 86400000;

function at(daysAgo: number, hours: number, minutes: number): string {
  const d = new Date(Date.now() - daysAgo * DAY);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

function daysFromNow(days: number): string {
  return new Date(Date.now() + days * DAY).toISOString();
}

export function seedState(locale: Locale = 'pt'): AtlasState {
  // Local translator bound to the requested locale.
  const t = (key: string, params?: Record<string, string | number>) => translate(key, params, locale);

  // Deterministic id sequence — identical on every call, so a re-seed
  // (e.g. language change) can merge with user-created entities by id.
  let seq = 0;
  const sid = (prefix: string): string => {
    seq += 1;
    return `${prefix}-${String(seq).padStart(2, '0')}`;
  };

  const activities = [
    { id: sid('act'), time: at(0, 9, 42), kind: 'agent' as const, actor: 'SCOUT', title: t('Found 7 high-intent prospects.'), detail: t('Scored against ICP — threshold 75.'), tone: 'success' as const },
    { id: sid('act'), time: at(0, 9, 37), kind: 'system' as const, actor: 'ATLAS', title: t('Generated the ORBITA SEO checklist.'), detail: t('18 issues triaged by severity.'), tone: 'info' as const },
    { id: sid('act'), time: at(0, 9, 21), kind: 'agent' as const, actor: 'RESEARCH', title: t('Completed competitor analysis.'), detail: t('6 competitors mapped.'), tone: 'success' as const },
    { id: sid('act'), time: at(0, 8, 54), kind: 'agent' as const, actor: 'EXECUTION', title: t('Detected a deployment issue on ORBITA.'), detail: t('Missing environment variables.'), tone: 'error' as const },
    { id: sid('act'), time: at(0, 8, 31), kind: 'agent' as const, actor: 'CONTENT', title: t('Drafted 3 campaign assets.'), detail: t('Waiting for your review.'), tone: 'info' as const },
    { id: sid('act'), time: at(0, 8, 12), kind: 'agent' as const, actor: 'SEO', title: t('Found 18 SEO issues on ORBITA.'), detail: t('4 safe fixes available.'), tone: 'warning' as const },
    { id: sid('act'), time: at(0, 7, 58), kind: 'system' as const, actor: 'ATLAS', title: t('Compiled your morning briefing.'), tone: 'info' as const },
    { id: sid('act'), time: at(1, 18, 20), kind: 'agent' as const, actor: 'SCOUT', title: t('Qualified 12 prospects.'), tone: 'success' as const },
    { id: sid('act'), time: at(1, 17, 45), kind: 'system' as const, actor: 'ATLAS', title: t('Updated the revenue projection.'), detail: t('Projected €980 against a €1,000 target.'), tone: 'info' as const },
    { id: sid('act'), time: at(1, 16, 3), kind: 'agent' as const, actor: 'RESEARCH', title: t('Mapped 6 competitors in your niche.'), tone: 'success' as const },
    { id: sid('act'), time: at(1, 15, 30), kind: 'system' as const, actor: 'ATLAS', title: t('WEAF catalog reached 91%.'), detail: t('One item remaining: bundle builder.'), tone: 'info' as const },
    { id: sid('act'), time: at(1, 11, 2), kind: 'agent' as const, actor: 'CONTENT', title: t('Published catalog copy to WEAF.'), tone: 'success' as const },
    { id: sid('act'), time: at(1, 9, 14), kind: 'agent' as const, actor: 'SCOUT', title: t('Detected pricing-page signals.'), detail: t('3 prospects visited pricing twice.'), tone: 'info' as const },
  ];

  const goals = [
    {
      id: 'g-revenue',
      title: t('€1,000 monthly revenue'),
      objective: t('Reach €1,000 in monthly recurring revenue from premium websites and AI automation.'),
      unit: 'currency' as const,
      target: 1000,
      current: 680,
      projected: 980,
      currency: 'EUR' as const,
      deadline: daysFromNow(23),
      status: 'on-track' as const,
      strategy: [t('Premium websites'), t('AI automation'), t('Outbound acquisition')],
      assumptions: [
        t('7 qualified prospects / day'),
        t('3 conversations / day'),
        t('1 proposal / day'),
        t('1–2 clients / month'),
        t('Average project value €4,500'),
      ],
      milestones: [
        { id: sid('ms'), title: t('First paying client'), status: 'done' as const, dueDate: at(50, 12, 0) },
        { id: sid('ms'), title: t('3 discovery calls booked'), status: 'done' as const, dueDate: at(36, 12, 0) },
        { id: sid('ms'), title: t('2 proposals sent'), status: 'active' as const, dueDate: daysFromNow(3) },
        { id: sid('ms'), title: t('Close first €1,000/mo client'), status: 'todo' as const },
        { id: sid('ms'), title: t('Reach €1,000 MRR'), status: 'todo' as const },
      ],
      risks: [
        t('Outbound reply rate is declining (12% → 7%)'),
        t('ORBITA launch delay weakens proof for prospects'),
        t('Pipeline depends on a daily prospecting cadence'),
      ],
      nextActions: [
        t('Contact 7 high-intent leads'),
        t('Send the 2 pending proposals'),
        t('Connect Gmail to send approved messages'),
      ],
      aiRecommendation: t('Your reply rate dropped from 12% to 7% this week. Test a shorter first message with SCOUT before scaling volume.'),
      createdAt: at(67, 9, 0),
      updatedAt: at(0, 7, 58),
    },
    {
      id: 'g-launch',
      title: t('Launch ORBITA'),
      objective: t('Ship the ORBITA portfolio site — the flagship proof asset for the studio.'),
      unit: 'percent' as const,
      target: 100,
      current: 82,
      deadline: daysFromNow(6),
      status: 'at-risk' as const,
      strategy: [t('Finish technical checklist'), t('Resolve deployment'), t('Verify live')],
      assumptions: [t('Launch date holds if deployment unblocks this week')],
      milestones: [
        { id: sid('ms'), title: t('Research & positioning'), status: 'done' as const },
        { id: sid('ms'), title: t('Design & build'), status: 'done' as const },
        { id: sid('ms'), title: t('SEO audit'), status: 'active' as const },
        { id: sid('ms'), title: t('Deployment'), status: 'todo' as const },
      ],
      risks: [t('Deployment is blocked — Vercel is not connected')],
      nextActions: [t('Connect Vercel and set environment variables'), t('Finish the SEO audit')],
      aiRecommendation: t('The launch date is at risk. Unblocking deployment matters more than any content work today.'),
      linkedProjectId: 'p-orbita',
      createdAt: at(40, 9, 0),
      updatedAt: at(0, 8, 54),
    },
    {
      id: 'g-outbound',
      title: t('5 qualified conversations per week'),
      objective: t('Build a repeatable outbound rhythm that fills the top of the funnel.'),
      unit: 'count' as const,
      target: 5,
      current: 3,
      deadline: daysFromNow(84),
      status: 'on-track' as const,
      strategy: [t('Daily prospecting'), t('Personalized first lines'), t('Fast follow-up')],
      assumptions: [t('Reply rate recovers with a shorter message'), t('7 prospects/day is sustainable')],
      milestones: [
        { id: sid('ms'), title: t('ICP scoring model live'), status: 'done' as const },
        { id: sid('ms'), title: t('Outreach sequence drafted'), status: 'done' as const },
        { id: sid('ms'), title: t('3 conversations / week'), status: 'done' as const },
        { id: sid('ms'), title: t('5 conversations / week'), status: 'active' as const },
      ],
      risks: [t('Message fatigue if volume scales too fast')],
      nextActions: [t('Contact today’s high-intent queue'), t('Test the shorter message variant')],
      aiRecommendation: t('You are at 3 of 5 weekly conversations. Today’s 7 prospects are enough to close the gap.'),
      createdAt: at(28, 9, 0),
      updatedAt: at(1, 17, 45),
    },
  ];

  const projects = [
    {
      id: 'p-orbita',
      name: 'ORBITA',
      objective: t('Portfolio and lead-generation website for the studio. The flagship launch.'),
      status: 'blocked' as const,
      deadline: daysFromNow(6),
      milestones: [
        { id: sid('ms'), title: t('Research'), status: 'done' as const },
        { id: sid('ms'), title: t('Positioning'), status: 'done' as const },
        { id: sid('ms'), title: t('Brand identity'), status: 'done' as const },
        { id: sid('ms'), title: t('Copy'), status: 'done' as const },
        { id: sid('ms'), title: t('Design'), status: 'done' as const },
        { id: sid('ms'), title: t('Homepage build'), status: 'done' as const },
        { id: sid('ms'), title: t('Pricing page'), status: 'done' as const },
        { id: sid('ms'), title: t('Case studies'), status: 'done' as const },
        { id: sid('ms'), title: t('Blog setup'), status: 'done' as const },
        { id: sid('ms'), title: t('SEO audit'), status: 'active' as const },
        { id: sid('ms'), title: t('Deployment'), status: 'todo' as const },
      ],
      blockers: [
        {
          id: sid('blk'),
          title: t('Deployment configuration'),
          reason: t('Missing environment variables. The Vercel integration is not connected.'),
          severity: 'high' as const,
          integrationId: 'vercel',
        },
      ],
      agentIds: ['a-seo', 'a-execution', 'a-deployment'],
      nextAction: t('Connect Vercel and set environment variables.'),
      createdAt: at(45, 9, 0),
      updatedAt: at(0, 8, 54),
    },
    {
      id: 'p-scout',
      name: 'SCOUT',
      objective: t('Outbound prospecting engine: find, score and qualify prospects every day.'),
      status: 'active' as const,
      milestones: [
        { id: sid('ms'), title: t('ICP definition'), status: 'done' as const },
        { id: sid('ms'), title: t('Source list'), status: 'done' as const },
        { id: sid('ms'), title: t('Data enrichment pipeline'), status: 'done' as const },
        { id: sid('ms'), title: t('Scoring model'), status: 'done' as const },
        { id: sid('ms'), title: t('Batch 1 — 25 prospects'), status: 'done' as const },
        { id: sid('ms'), title: t('Batch 2 — 40 prospects'), status: 'done' as const },
        { id: sid('ms'), title: t('Outreach sequence'), status: 'done' as const },
        { id: sid('ms'), title: t('Daily prospecting'), status: 'active' as const },
        { id: sid('ms'), title: t('Reply monitoring'), status: 'todo' as const },
        { id: sid('ms'), title: t('CRM sync'), status: 'todo' as const },
        { id: sid('ms'), title: t('Weekly review'), status: 'todo' as const },
      ],
      blockers: [],
      agentIds: ['a-scout'],
      nextAction: t('Contact 7 high-intent leads.'),
      createdAt: at(60, 9, 0),
      updatedAt: at(0, 9, 42),
    },
    {
      id: 'p-weaf',
      name: 'WEAF',
      objective: t('WooCommerce storefront for curated tools and gear.'),
      status: 'active' as const,
      milestones: [
        { id: sid('ms'), title: t('Catalog structure'), status: 'done' as const },
        { id: sid('ms'), title: t('32 products imported'), status: 'done' as const },
        { id: sid('ms'), title: t('Photography'), status: 'done' as const },
        { id: sid('ms'), title: t('Pricing'), status: 'done' as const },
        { id: sid('ms'), title: t('Descriptions'), status: 'done' as const },
        { id: sid('ms'), title: t('Categories'), status: 'done' as const },
        { id: sid('ms'), title: t('Shipping'), status: 'done' as const },
        { id: sid('ms'), title: t('Payments'), status: 'done' as const },
        { id: sid('ms'), title: t('Store SEO'), status: 'done' as const },
        { id: sid('ms'), title: t('Reviews'), status: 'done' as const },
        { id: sid('ms'), title: t('Bundle builder'), status: 'active' as const },
      ],
      blockers: [],
      agentIds: ['a-content'],
      nextAction: t('Complete the last catalog item — the bundle builder.'),
      createdAt: at(52, 9, 0),
      updatedAt: at(1, 15, 30),
    },
  ];

  const agents = [
    {
      id: 'a-scout',
      name: 'SCOUT',
      purpose: t('Finds and qualifies prospects.'),
      status: 'running' as const,
      currentTask: t('Morning prospect sweep'),
      progress: 64,
      tools: [t('Web search'), 'LinkedIn', 'Apollo', 'Clearbit'],
      permissionLevel: 2 as const,
      approvalRequired: true,
      results: [t('7 high-intent prospects queued'), t('ICP scoring model v2 deployed')],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 9, 42), title: t('Found 7 high-intent prospects.'), tone: 'success' as const },
        { id: sid('agact'), time: at(1, 18, 20), title: t('Qualified 12 prospects.'), tone: 'success' as const },
      ],
      lastRunAt: at(0, 9, 42),
    },
    {
      id: 'a-research',
      name: 'RESEARCH',
      purpose: t('Researches markets, competitors and opportunities.'),
      status: 'completed' as const,
      currentTask: t('Competitor analysis'),
      progress: 100,
      tools: [t('Web search'), 'Crunchbase', 'SimilarWeb'],
      permissionLevel: 1 as const,
      approvalRequired: false,
      results: [t('Competitor analysis completed — 6 competitors mapped'), t('Positioning gap found: AI automation')],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 9, 21), title: t('Completed competitor analysis.'), tone: 'success' as const },
      ],
      lastRunAt: at(0, 9, 21),
    },
    {
      id: 'a-content',
      name: 'CONTENT',
      purpose: t('Creates content and campaign assets.'),
      status: 'waiting' as const,
      currentTask: t('Q4 campaign draft'),
      progress: 45,
      tools: [t('Copywriting'), 'CMS', t('Image generation')],
      permissionLevel: 2 as const,
      approvalRequired: true,
      results: [t('3 campaign assets drafted')],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 8, 31), title: t('Drafted 3 campaign assets.'), detail: t('Waiting for your review.'), tone: 'warning' as const },
      ],
    },
    {
      id: 'a-seo',
      name: 'SEO',
      purpose: t('Analyzes SEO opportunities and issues.'),
      status: 'running' as const,
      currentTask: t('ORBITA SEO audit'),
      progress: 60,
      tools: [t('Site crawl'), 'Search Console', 'Ahrefs'],
      permissionLevel: 1 as const,
      approvalRequired: false,
      results: [t('18 issues found'), t('Meta descriptions missing on 4 pages')],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 8, 12), title: t('Found 18 SEO issues on ORBITA.'), tone: 'warning' as const },
      ],
    },
    {
      id: 'a-execution',
      name: 'EXECUTION',
      purpose: t('Coordinates project execution.'),
      status: 'blocked' as const,
      currentTask: t('ORBITA deployment'),
      progress: 82,
      tools: ['GitHub', 'Vercel', 'CI'],
      permissionLevel: 3 as const,
      approvalRequired: true,
      results: [t('Build passing'), t('Preview deployments ready')],
      errors: [t('Missing environment variables: DATABASE_URL, STRIPE_KEY')],
      activity: [
        { id: sid('agact'), time: at(0, 8, 54), title: t('Deployment blocked.'), detail: t('Missing environment variables.'), tone: 'error' as const },
      ],
    },
    {
      id: 'a-deployment',
      name: 'DEPLOYMENT',
      purpose: t('Deploys and verifies production releases.'),
      status: 'idle' as const,
      currentTask: '—',
      progress: 0,
      tools: ['Vercel', 'GitHub Actions'],
      permissionLevel: 3 as const,
      approvalRequired: true,
      results: [],
      errors: [],
      activity: [],
    },
  ];

  const runs = [
    {
      id: 'r-research-done',
      agentId: 'a-research',
      objective: t('Competitor analysis — web studios in your niche'),
      kind: 'research' as const,
      status: 'completed' as const,
      steps: [
        { id: sid('step'), title: t('Define research scope'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: t('Gather sources'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: t('Synthesize findings'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: t('Deliver report'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
      ],
      currentStepIndex: 3,
      progress: 100,
      startedAt: at(0, 9, 0),
      finishedAt: at(0, 9, 21),
      result: t('6 competitors mapped. Positioning gap found in AI automation.'),
      createdBy: 'atlas' as const,
      approvalIds: [],
    },
    {
      id: 'r-deploy-blocked',
      agentId: 'a-execution',
      objective: t('Deploy ORBITA to production'),
      kind: 'deploy' as const,
      status: 'blocked' as const,
      steps: [
        { id: sid('step'), title: t('Build project'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: t('Run preview checks'), status: 'done' as const, ticks: 1, ticksLeft: 0 },
        {
          id: sid('step'),
          title: t('Configure environment variables'),
          detail: t('Requires a Vercel connection'),
          status: 'blocked' as const,
          integrationId: 'vercel',
          blockedReason: t('Vercel is not connected. Add the integration to configure environment variables.'),
          ticks: 1,
          ticksLeft: 0,
        },
        { id: sid('step'), title: t('Deploy to production'), status: 'pending' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: t('Verify live site'), status: 'pending' as const, ticks: 1, ticksLeft: 0 },
      ],
      currentStepIndex: 2,
      progress: 40,
      startedAt: at(0, 8, 40),
      error: t('Missing environment variables: DATABASE_URL, STRIPE_KEY. Vercel is not connected.'),
      createdBy: 'atlas' as const,
      linkedProjectId: 'p-orbita',
      approvalIds: [],
    },
  ];

  const approvals = [
    {
      id: 'ap-strategy',
      level: 3 as const,
      action: t('Approve Q4 outbound strategy'),
      description: t('ATLAS recommends: 7 qualified prospects/day, 3 conversations/day, 1 proposal/day.'),
      context: { agent: 'ATLAS', detail: t('Based on your current reply rate and pipeline.') },
      status: 'pending' as const,
      effect: { type: 'memory' as const, category: 'decisions' as const, text: t('Q4 outbound strategy approved: 7 prospects/day, 3 conversations/day, 1 proposal/day.') },
      createdAt: at(0, 9, 15),
    },
    {
      id: 'ap-followups',
      level: 3 as const,
      action: t('Send 3 follow-up messages'),
      description: t('SCOUT drafted follow-ups for 3 prospects who opened your last message.'),
      context: { agent: 'SCOUT', detail: t('3 messages · direct tone') },
      status: 'pending' as const,
      effect: { type: 'spawn-run' as const, agentId: 'a-scout', objective: t('Send 3 approved follow-up messages'), kind: 'send-approved' as const },
      createdAt: at(0, 9, 37),
    },
  ];

  const opportunities = [
    {
      id: 'o-1',
      company: 'Nordwind Studio',
      person: 'Lena Hartmann',
      role: t('Founder'),
      matchScore: 94,
      signals: [t('Matches ideal customer profile'), t('Viewed your portfolio twice this week')],
      status: 'new' as const,
      source: 'LinkedIn',
      domain: 'nordwind.studio',
      country: 'Germany',
      createdAt: at(0, 9, 42),
    },
    {
      id: 'o-2',
      company: 'Kavo Foods',
      person: 'Rui Costa',
      role: 'CEO',
      matchScore: 91,
      signals: [t('Matches ideal customer profile'), t('Website is outdated — clear opportunity'), t('Posted about a rebrand last week')],
      status: 'new' as const,
      source: 'LinkedIn',
      domain: 'kavofoods.pt',
      country: 'Portugal',
      createdAt: at(0, 9, 41),
    },
    {
      id: 'o-3',
      company: 'Lumen Realty',
      person: 'Sara Vidal',
      role: t('Marketing Director'),
      matchScore: 88,
      signals: [t('Recently interacted with your site'), t('Visited the pricing page twice')],
      status: 'new' as const,
      source: t('Website'),
      domain: 'lumenrealty.pt',
      country: 'Portugal',
      createdAt: at(0, 9, 38),
    },
    {
      id: 'o-4',
      company: 'Brava Labs',
      person: 'Tomás Reis',
      role: t('Founder'),
      matchScore: 86,
      signals: [t('Matches ideal customer profile'), t('Hiring a web developer — timing signal')],
      status: 'new' as const,
      source: 'LinkedIn',
      domain: 'bravalabs.com',
      country: 'Portugal',
      createdAt: at(0, 9, 35),
    },
    {
      id: 'o-5',
      company: 'Porto & Co',
      person: 'Marta Lima',
      role: t('Partner'),
      matchScore: 84,
      signals: [t('Website is outdated — clear opportunity')],
      status: 'new' as const,
      source: t('Web search'),
      domain: 'portoandco.pt',
      country: 'Portugal',
      createdAt: at(0, 9, 30),
    },
    {
      id: 'o-6',
      company: 'Fieldnote',
      person: 'Ana Belo',
      role: 'COO',
      matchScore: 82,
      signals: [t('Recently raised a seed round — budget signal'), t('Visited the pricing page')],
      status: 'new' as const,
      source: t('Web search'),
      domain: 'fieldnote.io',
      country: 'United Kingdom',
      createdAt: at(0, 9, 25),
    },
    {
      id: 'o-7',
      company: 'Halden',
      person: 'Jonas Weber',
      role: t('Managing Director'),
      matchScore: 79,
      signals: [t('Matches ideal customer profile'), t('Visited the portfolio this week')],
      status: 'new' as const,
      source: 'LinkedIn',
      domain: 'halden.se',
      country: 'Sweden',
      createdAt: at(0, 9, 20),
    },
  ];

  const insights = [
    {
      id: sid('ins'),
      type: 'opportunity' as const,
      title: t('3 companies match your ideal client profile.'),
      description: t('Nordwind Studio, Kavo Foods and Brava Labs all fit your ICP and are actively looking for web work.'),
      whyItMatters: t('These are your highest-intent prospects — the fastest path to revenue this week.'),
      recommendation: t('Contact them today. SCOUT has already drafted personalized messages.'),
      actionLabel: t('Review outreach'),
      actionKind: 'execute-nba' as const,
      severity: 'high' as const,
      createdAt: at(0, 9, 42),
    },
    {
      id: sid('ins'),
      type: 'risk' as const,
      title: t('The ORBITA launch is delayed by deployment.'),
      description: t('Environment variables are missing and the Vercel integration is not connected.'),
      whyItMatters: t('Your launch date is in 6 days — and ORBITA is your primary proof asset for prospects.'),
      recommendation: t('Connect Vercel, set the environment variables, then deploy.'),
      actionLabel: t('Connect Vercel'),
      actionKind: 'connect' as const,
      integrationId: 'vercel',
      projectId: 'p-orbita',
      severity: 'high' as const,
      createdAt: at(0, 8, 54),
    },
    {
      id: sid('ins'),
      type: 'signal' as const,
      title: t('Your outbound conversion rate decreased.'),
      description: t('Replies dropped from 12% to 7% over the last two weeks.'),
      whyItMatters: t('At the current rate, 7 prospects/day will not produce 3 conversations/day.'),
      recommendation: t('Test a shorter first message with SCOUT before scaling volume.'),
      actionLabel: t('Run the test'),
      actionKind: 'open-execution' as const,
      severity: 'medium' as const,
      createdAt: at(0, 8, 20),
    },
    {
      id: sid('ins'),
      type: 'trend' as const,
      title: t('AI automation is becoming a default client expectation.'),
      description: t('4 of your last 7 prospects asked about automation in their first message.'),
      whyItMatters: t('Positioning that leads with AI automation matches what the market is asking for.'),
      recommendation: t('Add an AI automation page to ORBITA before launch.'),
      actionLabel: t('View project'),
      actionKind: 'view-project' as const,
      projectId: 'p-orbita',
      severity: 'medium' as const,
      createdAt: at(0, 7, 30),
    },
    {
      id: sid('ins'),
      type: 'blocker' as const,
      title: t('The WEAF catalog is 91% complete.'),
      description: t('Only the bundle builder remains.'),
      whyItMatters: t('A finished catalog is a live store — one approval away.'),
      recommendation: t('Let the CONTENT agent draft the missing copy, then approve it.'),
      actionLabel: t('Complete catalog'),
      actionKind: 'open-execution' as const,
      projectId: 'p-weaf',
      severity: 'low' as const,
      createdAt: at(1, 15, 30),
    },
  ];

  const memories = [
    { id: sid('mem'), category: 'goals' as const, key: t('Primary goal'), value: t('€1,000/month within 90 days.'), updatedAt: at(0, 7, 58) },
    { id: sid('mem'), category: 'projects' as const, key: 'ORBITA', value: t('Flagship portfolio launch. Deadline: October 14.'), updatedAt: at(0, 8, 54) },
    { id: sid('mem'), category: 'projects' as const, key: 'WEAF', value: t('WooCommerce storefront, 91% complete.'), updatedAt: at(1, 15, 30) },
    { id: sid('mem'), category: 'preferences' as const, key: t('Tone'), value: t('Short, direct messages. No fluff.'), updatedAt: at(20, 10, 0) },
    { id: sid('mem'), category: 'preferences' as const, key: t('Best contact window'), value: t('09:00–11:00, Europe/Lisbon.'), updatedAt: at(20, 10, 0) },
    { id: sid('mem'), category: 'skills' as const, key: t('Core skills'), value: t('Web design, Next.js, SEO, outbound sales, copywriting.'), updatedAt: at(30, 10, 0) },
    { id: sid('mem'), category: 'decisions' as const, key: t('Positioning'), value: t('Premium websites + AI automation.'), updatedAt: at(35, 10, 0) },
    { id: sid('mem'), category: 'decisions' as const, key: t('Pricing'), value: t('€3,500–€8,000 per project.'), updatedAt: at(35, 10, 0) },
    { id: sid('mem'), category: 'context' as const, key: t('Brand'), value: t('Building a personal brand around AI automation.'), updatedAt: at(12, 10, 0) },
  ];

  const integrations = [
    {
      id: 'google-calendar',
      name: 'Google Calendar',
      provider: 'Google',
      description: t('Read your calendar to protect focus time and schedule execution blocks.'),
      icon: Calendar,
      connected: false,
      scopes: ['calendar.read', 'calendar.events'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'gmail',
      name: 'Gmail',
      provider: 'Google',
      description: t('Send approved outreach and follow-ups on your behalf.'),
      icon: Mail,
      connected: false,
      scopes: ['gmail.send', 'gmail.read'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'google-drive',
      name: 'Google Drive',
      provider: 'Google',
      description: t('Store briefings, reports and campaign assets.'),
      icon: HardDrive,
      connected: false,
      scopes: ['drive.file'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'github',
      name: 'GitHub',
      provider: 'GitHub',
      description: t('Track commits, PRs and repository state for every project.'),
      icon: Github,
      connected: false,
      scopes: ['repo', 'read:user'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'vercel',
      name: 'Vercel',
      provider: 'Vercel',
      description: t('Deploy ORBITA and WEAF, and manage environment variables.'),
      icon: Triangle,
      connected: false,
      scopes: ['deployments', 'env', 'projects'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'slack',
      name: 'Slack',
      provider: 'Slack',
      description: t('Post briefings and agent updates where your team sees them.'),
      icon: Slack,
      connected: false,
      scopes: ['chat:write', 'channels:read'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp',
      provider: 'Meta',
      description: t('Send approved messages to prospects from your own number.'),
      icon: MessageCircle,
      connected: false,
      scopes: ['messages.send'],
      adapterStatus: 'beta' as const,
    },
    {
      id: 'stripe',
      name: 'Stripe',
      provider: 'Stripe',
      description: t('Measure real revenue against your goals. Read-only by default.'),
      icon: CreditCard,
      connected: false,
      scopes: ['balance.read', 'charges.read'],
      adapterStatus: 'ready' as const,
    },
  ];

  return {
    user: {
      id: 'u-chelton',
      name: 'Chelton',
      email: 'chelton@atlas.run',
      timezone: 'Europe/Lisbon',
      currency: 'EUR',
      role: t('Founder'),
    },
    preferences: {
      defaultPermissionLevel: 2,
      briefingEnabled: true,
      briefingTime: '08:00',
      weekStartsOn: 1,
      currency: 'EUR',
      language: locale,
    },
    apiConfig: {
      enabled: {
        github: true,
        npm: true,
        'rest-countries': true,
        frankfurter: true,
        'hacker-news': true,
        'stack-exchange': true,
        'dev-to': true,
        wikipedia: true,
        quotable: true,
        clearbit: true,
        nationalize: true,
        ipify: true,
      },
      features: {
        liveRates: true,
        liveSignals: true,
        prospectEnrichment: true,
        dailyQuote: true,
        githubStats: true,
      },
      githubRepo: 'vercel/next.js',
    },
    goals,
    projects,
    agents,
    runs,
    approvals,
    activities,
    insights,
    opportunities,
    memories,
    integrations,
    toasts: [],
    hydrated: false,
  } as AtlasState;
}
