import {
  Calendar,
  CreditCard,
  Github,
  HardDrive,
  Mail,
  MessageCircle,
  Slack,
  Triangle,
} from 'lucide-react';
import type { AtlasState } from './types';

// Seed data is generated relative to "now" so the product always
// opens in a believable, current state.

const DAY = 86400000;

function at(daysAgo: number, hours: number, minutes: number): string {
  const d = new Date(Date.now() - daysAgo * DAY);
  d.setHours(hours, minutes, 0, 0);
  return d.toISOString();
}

function daysFromNow(days: number): string {
  return new Date(Date.now() + days * DAY).toISOString();
}

let seq = 0;
function sid(prefix: string): string {
  seq += 1;
  return `${prefix}-${String(seq).padStart(2, '0')}`;
}

export function seedState(): AtlasState {
  const activities = [
    { id: sid('act'), time: at(0, 9, 42), kind: 'agent' as const, actor: 'SCOUT', title: 'Found 7 high-intent prospects.', detail: 'Scored against ICP — threshold 75.', tone: 'success' as const },
    { id: sid('act'), time: at(0, 9, 37), kind: 'system' as const, actor: 'ATLAS', title: 'Generated the ORBITA SEO checklist.', detail: '18 issues triaged by severity.', tone: 'info' as const },
    { id: sid('act'), time: at(0, 9, 21), kind: 'agent' as const, actor: 'RESEARCH', title: 'Completed competitor analysis.', detail: '6 competitors mapped.', tone: 'success' as const },
    { id: sid('act'), time: at(0, 8, 54), kind: 'agent' as const, actor: 'EXECUTION', title: 'Detected a deployment issue on ORBITA.', detail: 'Missing environment variables.', tone: 'error' as const },
    { id: sid('act'), time: at(0, 8, 31), kind: 'agent' as const, actor: 'CONTENT', title: 'Drafted 3 campaign assets.', detail: 'Waiting for your review.', tone: 'info' as const },
    { id: sid('act'), time: at(0, 8, 12), kind: 'agent' as const, actor: 'SEO', title: 'Found 18 SEO issues on ORBITA.', detail: '4 safe fixes available.', tone: 'warning' as const },
    { id: sid('act'), time: at(0, 7, 58), kind: 'system' as const, actor: 'ATLAS', title: 'Compiled your morning briefing.', tone: 'info' as const },
    { id: sid('act'), time: at(1, 18, 20), kind: 'agent' as const, actor: 'SCOUT', title: 'Qualified 12 prospects.', tone: 'success' as const },
    { id: sid('act'), time: at(1, 17, 45), kind: 'system' as const, actor: 'ATLAS', title: 'Updated the revenue projection.', detail: 'Projected €980 against a €1,000 target.', tone: 'info' as const },
    { id: sid('act'), time: at(1, 16, 3), kind: 'agent' as const, actor: 'RESEARCH', title: 'Mapped 6 competitors in your niche.', tone: 'success' as const },
    { id: sid('act'), time: at(1, 15, 30), kind: 'system' as const, actor: 'ATLAS', title: 'WEAF catalog reached 91%.', detail: 'One item remaining: bundle builder.', tone: 'info' as const },
    { id: sid('act'), time: at(1, 11, 2), kind: 'agent' as const, actor: 'CONTENT', title: 'Published catalog copy to WEAF.', tone: 'success' as const },
    { id: sid('act'), time: at(1, 9, 14), kind: 'agent' as const, actor: 'SCOUT', title: 'Detected pricing-page signals.', detail: '3 prospects visited pricing twice.', tone: 'info' as const },
  ];

  const goals = [
    {
      id: 'g-revenue',
      title: '€1,000 monthly revenue',
      objective: 'Reach €1,000 in monthly recurring revenue from premium websites and AI automation.',
      unit: 'currency' as const,
      target: 1000,
      current: 680,
      projected: 980,
      currency: 'EUR' as const,
      deadline: daysFromNow(23),
      status: 'on-track' as const,
      strategy: ['Premium websites', 'AI automation', 'Outbound acquisition'],
      assumptions: [
        '7 qualified prospects / day',
        '3 conversations / day',
        '1 proposal / day',
        '1–2 clients / month',
        'Average project value €4,500',
      ],
      milestones: [
        { id: sid('ms'), title: 'First paying client', status: 'done' as const, dueDate: at(50, 12, 0) },
        { id: sid('ms'), title: '3 discovery calls booked', status: 'done' as const, dueDate: at(36, 12, 0) },
        { id: sid('ms'), title: '2 proposals sent', status: 'active' as const, dueDate: daysFromNow(3) },
        { id: sid('ms'), title: 'Close first €1,000/mo client', status: 'todo' as const },
        { id: sid('ms'), title: 'Reach €1,000 MRR', status: 'todo' as const },
      ],
      risks: [
        'Outbound reply rate is declining (12% → 7%)',
        'ORBITA launch delay weakens proof for prospects',
        'Pipeline depends on a daily prospecting cadence',
      ],
      nextActions: [
        'Contact 7 high-intent leads',
        'Send the 2 pending proposals',
        'Connect Gmail to send approved messages',
      ],
      aiRecommendation:
        'Your reply rate dropped from 12% to 7% this week. Test a shorter first message with SCOUT before scaling volume.',
      createdAt: at(67, 9, 0),
      updatedAt: at(0, 7, 58),
    },
    {
      id: 'g-launch',
      title: 'Launch ORBITA',
      objective: 'Ship the ORBITA portfolio site — the flagship proof asset for the studio.',
      unit: 'percent' as const,
      target: 100,
      current: 82,
      deadline: daysFromNow(6),
      status: 'at-risk' as const,
      strategy: ['Finish technical checklist', 'Resolve deployment', 'Verify live'],
      assumptions: ['Launch date holds if deployment unblocks this week'],
      milestones: [
        { id: sid('ms'), title: 'Research & positioning', status: 'done' as const },
        { id: sid('ms'), title: 'Design & build', status: 'done' as const },
        { id: sid('ms'), title: 'SEO audit', status: 'active' as const },
        { id: sid('ms'), title: 'Deployment', status: 'todo' as const },
      ],
      risks: ['Deployment is blocked — Vercel is not connected'],
      nextActions: ['Connect Vercel and set environment variables', 'Finish the SEO audit'],
      aiRecommendation: 'The launch date is at risk. Unblocking deployment matters more than any content work today.',
      linkedProjectId: 'p-orbita',
      createdAt: at(40, 9, 0),
      updatedAt: at(0, 8, 54),
    },
    {
      id: 'g-outbound',
      title: '5 qualified conversations per week',
      objective: 'Build a repeatable outbound rhythm that fills the top of the funnel.',
      unit: 'count' as const,
      target: 5,
      current: 3,
      deadline: daysFromNow(84),
      status: 'on-track' as const,
      strategy: ['Daily prospecting', 'Personalized first lines', 'Fast follow-up'],
      assumptions: ['Reply rate recovers with a shorter message', '7 prospects/day is sustainable'],
      milestones: [
        { id: sid('ms'), title: 'ICP scoring model live', status: 'done' as const },
        { id: sid('ms'), title: 'Outreach sequence drafted', status: 'done' as const },
        { id: sid('ms'), title: '3 conversations / week', status: 'done' as const },
        { id: sid('ms'), title: '5 conversations / week', status: 'active' as const },
      ],
      risks: ['Message fatigue if volume scales too fast'],
      nextActions: ['Contact today’s high-intent queue', 'Test the shorter message variant'],
      aiRecommendation: 'You are at 3 of 5 weekly conversations. Today’s 7 prospects are enough to close the gap.',
      createdAt: at(28, 9, 0),
      updatedAt: at(1, 17, 45),
    },
  ];

  const projects = [
    {
      id: 'p-orbita',
      name: 'ORBITA',
      objective: 'Portfolio and lead-generation website for the studio. The flagship launch.',
      status: 'blocked' as const,
      deadline: daysFromNow(6),
      milestones: [
        { id: sid('ms'), title: 'Research', status: 'done' as const },
        { id: sid('ms'), title: 'Positioning', status: 'done' as const },
        { id: sid('ms'), title: 'Brand identity', status: 'done' as const },
        { id: sid('ms'), title: 'Copy', status: 'done' as const },
        { id: sid('ms'), title: 'Design', status: 'done' as const },
        { id: sid('ms'), title: 'Homepage build', status: 'done' as const },
        { id: sid('ms'), title: 'Pricing page', status: 'done' as const },
        { id: sid('ms'), title: 'Case studies', status: 'done' as const },
        { id: sid('ms'), title: 'Blog setup', status: 'done' as const },
        { id: sid('ms'), title: 'SEO audit', status: 'active' as const },
        { id: sid('ms'), title: 'Deployment', status: 'todo' as const },
      ],
      blockers: [
        {
          id: sid('blk'),
          title: 'Deployment configuration',
          reason: 'Missing environment variables. The Vercel integration is not connected.',
          severity: 'high' as const,
          integrationId: 'vercel',
        },
      ],
      agentIds: ['a-seo', 'a-execution', 'a-deployment'],
      nextAction: 'Connect Vercel and set environment variables.',
      createdAt: at(45, 9, 0),
      updatedAt: at(0, 8, 54),
    },
    {
      id: 'p-scout',
      name: 'SCOUT',
      objective: 'Outbound prospecting engine: find, score and qualify prospects every day.',
      status: 'active' as const,
      milestones: [
        { id: sid('ms'), title: 'ICP definition', status: 'done' as const },
        { id: sid('ms'), title: 'Source list', status: 'done' as const },
        { id: sid('ms'), title: 'Data enrichment pipeline', status: 'done' as const },
        { id: sid('ms'), title: 'Scoring model', status: 'done' as const },
        { id: sid('ms'), title: 'Batch 1 — 25 prospects', status: 'done' as const },
        { id: sid('ms'), title: 'Batch 2 — 40 prospects', status: 'done' as const },
        { id: sid('ms'), title: 'Outreach sequence', status: 'done' as const },
        { id: sid('ms'), title: 'Daily prospecting', status: 'active' as const },
        { id: sid('ms'), title: 'Reply monitoring', status: 'todo' as const },
        { id: sid('ms'), title: 'CRM sync', status: 'todo' as const },
        { id: sid('ms'), title: 'Weekly review', status: 'todo' as const },
      ],
      blockers: [],
      agentIds: ['a-scout'],
      nextAction: 'Contact 7 high-intent leads.',
      createdAt: at(60, 9, 0),
      updatedAt: at(0, 9, 42),
    },
    {
      id: 'p-weaf',
      name: 'WEAF',
      objective: 'WooCommerce storefront for curated tools and gear.',
      status: 'active' as const,
      milestones: [
        { id: sid('ms'), title: 'Catalog structure', status: 'done' as const },
        { id: sid('ms'), title: '32 products imported', status: 'done' as const },
        { id: sid('ms'), title: 'Photography', status: 'done' as const },
        { id: sid('ms'), title: 'Pricing', status: 'done' as const },
        { id: sid('ms'), title: 'Descriptions', status: 'done' as const },
        { id: sid('ms'), title: 'Categories', status: 'done' as const },
        { id: sid('ms'), title: 'Shipping', status: 'done' as const },
        { id: sid('ms'), title: 'Payments', status: 'done' as const },
        { id: sid('ms'), title: 'Store SEO', status: 'done' as const },
        { id: sid('ms'), title: 'Reviews', status: 'done' as const },
        { id: sid('ms'), title: 'Bundle builder', status: 'active' as const },
      ],
      blockers: [],
      agentIds: ['a-content'],
      nextAction: 'Complete the last catalog item — the bundle builder.',
      createdAt: at(52, 9, 0),
      updatedAt: at(1, 15, 30),
    },
  ];

  const agents = [
    {
      id: 'a-scout',
      name: 'SCOUT',
      purpose: 'Finds and qualifies prospects.',
      status: 'running' as const,
      currentTask: 'Morning prospect sweep',
      progress: 64,
      tools: ['Web search', 'LinkedIn', 'Apollo', 'Clearbit'],
      permissionLevel: 2 as const,
      approvalRequired: true,
      results: ['7 high-intent prospects queued', 'ICP scoring model v2 deployed'],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 9, 42), title: 'Found 7 high-intent prospects.', tone: 'success' as const },
        { id: sid('agact'), time: at(1, 18, 20), title: 'Qualified 12 prospects.', tone: 'success' as const },
      ],
      lastRunAt: at(0, 9, 42),
    },
    {
      id: 'a-research',
      name: 'RESEARCH',
      purpose: 'Researches markets, competitors and opportunities.',
      status: 'completed' as const,
      currentTask: 'Competitor analysis',
      progress: 100,
      tools: ['Web search', 'Crunchbase', 'SimilarWeb'],
      permissionLevel: 1 as const,
      approvalRequired: false,
      results: ['Competitor analysis completed — 6 competitors mapped', 'Positioning gap found: AI automation'],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 9, 21), title: 'Completed competitor analysis.', tone: 'success' as const },
      ],
      lastRunAt: at(0, 9, 21),
    },
    {
      id: 'a-content',
      name: 'CONTENT',
      purpose: 'Creates content and campaign assets.',
      status: 'waiting' as const,
      currentTask: 'Q4 campaign draft',
      progress: 45,
      tools: ['Copywriting', 'CMS', 'Image generation'],
      permissionLevel: 2 as const,
      approvalRequired: true,
      results: ['3 campaign assets drafted'],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 8, 31), title: 'Drafted 3 campaign assets.', detail: 'Waiting for your review.', tone: 'warning' as const },
      ],
    },
    {
      id: 'a-seo',
      name: 'SEO',
      purpose: 'Analyzes SEO opportunities and issues.',
      status: 'running' as const,
      currentTask: 'ORBITA SEO audit',
      progress: 60,
      tools: ['Site crawl', 'Search Console', 'Ahrefs'],
      permissionLevel: 1 as const,
      approvalRequired: false,
      results: ['18 issues found', 'Meta descriptions missing on 4 pages'],
      errors: [],
      activity: [
        { id: sid('agact'), time: at(0, 8, 12), title: 'Found 18 SEO issues on ORBITA.', tone: 'warning' as const },
      ],
    },
    {
      id: 'a-execution',
      name: 'EXECUTION',
      purpose: 'Coordinates project execution.',
      status: 'blocked' as const,
      currentTask: 'ORBITA deployment',
      progress: 82,
      tools: ['GitHub', 'Vercel', 'CI'],
      permissionLevel: 3 as const,
      approvalRequired: true,
      results: ['Build passing', 'Preview deployments ready'],
      errors: ['Missing environment variables: DATABASE_URL, STRIPE_KEY'],
      activity: [
        { id: sid('agact'), time: at(0, 8, 54), title: 'Deployment blocked.', detail: 'Missing environment variables.', tone: 'error' as const },
      ],
    },
    {
      id: 'a-deployment',
      name: 'DEPLOYMENT',
      purpose: 'Deploys and verifies production releases.',
      status: 'idle' as const,
      currentTask: '—',
      progress: 0,
      tools: ['Vercel', 'GitHub Actions'],
      permissionLevel: 3 as const,
      approvalRequired: true,
      results: [],
      errors: [],
      activity: [],
    },
  ];

  const runs = [
    {
      id: 'r-research-done',
      agentId: 'a-research',
      objective: 'Competitor analysis — web studios in your niche',
      kind: 'research' as const,
      status: 'completed' as const,
      steps: [
        { id: sid('step'), title: 'Define research scope', status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: 'Gather sources', status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: 'Synthesize findings', status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: 'Deliver report', status: 'done' as const, ticks: 1, ticksLeft: 0 },
      ],
      currentStepIndex: 3,
      progress: 100,
      startedAt: at(0, 9, 0),
      finishedAt: at(0, 9, 21),
      result: '6 competitors mapped. Positioning gap found in AI automation.',
      createdBy: 'atlas' as const,
      approvalIds: [],
    },
    {
      id: 'r-deploy-blocked',
      agentId: 'a-execution',
      objective: 'Deploy ORBITA to production',
      kind: 'deploy' as const,
      status: 'blocked' as const,
      steps: [
        { id: sid('step'), title: 'Build project', status: 'done' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: 'Run preview checks', status: 'done' as const, ticks: 1, ticksLeft: 0 },
        {
          id: sid('step'),
          title: 'Configure environment variables',
          detail: 'Requires a Vercel connection',
          status: 'blocked' as const,
          integrationId: 'vercel',
          blockedReason: 'Vercel is not connected. Add the integration to configure environment variables.',
          ticks: 1,
          ticksLeft: 0,
        },
        { id: sid('step'), title: 'Deploy to production', status: 'pending' as const, ticks: 1, ticksLeft: 0 },
        { id: sid('step'), title: 'Verify live site', status: 'pending' as const, ticks: 1, ticksLeft: 0 },
      ],
      currentStepIndex: 2,
      progress: 40,
      startedAt: at(0, 8, 40),
      error: 'Missing environment variables: DATABASE_URL, STRIPE_KEY. Vercel is not connected.',
      createdBy: 'atlas' as const,
      linkedProjectId: 'p-orbita',
      approvalIds: [],
    },
  ];

  const approvals = [
    {
      id: 'ap-strategy',
      level: 3 as const,
      action: 'Approve Q4 outbound strategy',
      description: 'ATLAS recommends: 7 qualified prospects/day, 3 conversations/day, 1 proposal/day.',
      context: { agent: 'ATLAS', detail: 'Based on your current reply rate and pipeline.' },
      status: 'pending' as const,
      effect: { type: 'memory' as const, category: 'decisions' as const, text: 'Q4 outbound strategy approved: 7 prospects/day, 3 conversations/day, 1 proposal/day.' },
      createdAt: at(0, 9, 15),
    },
    {
      id: 'ap-followups',
      level: 3 as const,
      action: 'Send 3 follow-up messages',
      description: 'SCOUT drafted follow-ups for 3 prospects who opened your last message.',
      context: { agent: 'SCOUT', detail: '3 messages · direct tone' },
      status: 'pending' as const,
      effect: { type: 'spawn-run' as const, agentId: 'a-scout', objective: 'Send 3 approved follow-up messages', kind: 'send-approved' as const },
      createdAt: at(0, 9, 37),
    },
  ];

  const opportunities = [
    {
      id: 'o-1',
      company: 'Nordwind Studio',
      person: 'Lena Hartmann',
      role: 'Founder',
      matchScore: 94,
      signals: ['Matches ideal customer profile', 'Viewed your portfolio twice this week'],
      status: 'new' as const,
      source: 'LinkedIn',
      createdAt: at(0, 9, 42),
    },
    {
      id: 'o-2',
      company: 'Kavo Foods',
      person: 'Rui Costa',
      role: 'CEO',
      matchScore: 91,
      signals: ['Matches ideal customer profile', 'Website is outdated — clear opportunity', 'Posted about a rebrand last week'],
      status: 'new' as const,
      source: 'LinkedIn',
      createdAt: at(0, 9, 41),
    },
    {
      id: 'o-3',
      company: 'Lumen Realty',
      person: 'Sara Vidal',
      role: 'Marketing Director',
      matchScore: 88,
      signals: ['Recently interacted with your site', 'Visited the pricing page twice'],
      status: 'new' as const,
      source: 'Website',
      createdAt: at(0, 9, 38),
    },
    {
      id: 'o-4',
      company: 'Brava Labs',
      person: 'Tomás Reis',
      role: 'Founder',
      matchScore: 86,
      signals: ['Matches ideal customer profile', 'Hiring a web developer — timing signal'],
      status: 'new' as const,
      source: 'LinkedIn',
      createdAt: at(0, 9, 35),
    },
    {
      id: 'o-5',
      company: 'Porto & Co',
      person: 'Marta Lima',
      role: 'Partner',
      matchScore: 84,
      signals: ['Website is outdated — clear opportunity'],
      status: 'new' as const,
      source: 'Web search',
      createdAt: at(0, 9, 30),
    },
    {
      id: 'o-6',
      company: 'Fieldnote',
      person: 'Ana Belo',
      role: 'COO',
      matchScore: 82,
      signals: ['Recently raised a seed round — budget signal', 'Visited the pricing page'],
      status: 'new' as const,
      source: 'Web search',
      createdAt: at(0, 9, 25),
    },
    {
      id: 'o-7',
      company: 'Halden',
      person: 'Jonas Weber',
      role: 'Managing Director',
      matchScore: 79,
      signals: ['Matches ideal customer profile', 'Visited the portfolio this week'],
      status: 'new' as const,
      source: 'LinkedIn',
      createdAt: at(0, 9, 20),
    },
  ];

  const insights = [
    {
      id: sid('ins'),
      type: 'opportunity' as const,
      title: '3 companies match your ideal client profile.',
      description: 'Nordwind Studio, Kavo Foods and Brava Labs all fit your ICP and are actively looking for web work.',
      whyItMatters: 'These are your highest-intent prospects — the fastest path to revenue this week.',
      recommendation: 'Contact them today. SCOUT has already drafted personalized messages.',
      actionLabel: 'Review outreach',
      actionKind: 'execute-nba' as const,
      severity: 'high' as const,
      createdAt: at(0, 9, 42),
    },
    {
      id: sid('ins'),
      type: 'risk' as const,
      title: 'The ORBITA launch is delayed by deployment.',
      description: 'Environment variables are missing and the Vercel integration is not connected.',
      whyItMatters: 'Your launch date is in 6 days — and ORBITA is your primary proof asset for prospects.',
      recommendation: 'Connect Vercel, set the environment variables, then deploy.',
      actionLabel: 'Connect Vercel',
      actionKind: 'connect' as const,
      integrationId: 'vercel',
      projectId: 'p-orbita',
      severity: 'high' as const,
      createdAt: at(0, 8, 54),
    },
    {
      id: sid('ins'),
      type: 'signal' as const,
      title: 'Your outbound conversion rate decreased.',
      description: 'Replies dropped from 12% to 7% over the last two weeks.',
      whyItMatters: 'At the current rate, 7 prospects/day will not produce 3 conversations/day.',
      recommendation: 'Test a shorter first message with SCOUT before scaling volume.',
      actionLabel: 'Run the test',
      actionKind: 'open-execution' as const,
      severity: 'medium' as const,
      createdAt: at(0, 8, 20),
    },
    {
      id: sid('ins'),
      type: 'trend' as const,
      title: 'AI automation is becoming a default client expectation.',
      description: '4 of your last 7 prospects asked about automation in their first message.',
      whyItMatters: 'Positioning that leads with AI automation matches what the market is asking for.',
      recommendation: 'Add an AI automation page to ORBITA before launch.',
      actionLabel: 'View project',
      actionKind: 'view-project' as const,
      projectId: 'p-orbita',
      severity: 'medium' as const,
      createdAt: at(0, 7, 30),
    },
    {
      id: sid('ins'),
      type: 'blocker' as const,
      title: 'The WEAF catalog is 91% complete.',
      description: 'Only the bundle builder remains.',
      whyItMatters: 'A finished catalog is a live store — one approval away.',
      recommendation: 'Let the CONTENT agent draft the missing copy, then approve it.',
      actionLabel: 'Complete catalog',
      actionKind: 'open-execution' as const,
      projectId: 'p-weaf',
      severity: 'low' as const,
      createdAt: at(1, 15, 30),
    },
  ];

  const memories = [
    { id: sid('mem'), category: 'goals' as const, key: 'Primary goal', value: '€1,000/month within 90 days.', updatedAt: at(0, 7, 58) },
    { id: sid('mem'), category: 'projects' as const, key: 'ORBITA', value: 'Flagship portfolio launch. Deadline: October 14.', updatedAt: at(0, 8, 54) },
    { id: sid('mem'), category: 'projects' as const, key: 'WEAF', value: 'WooCommerce storefront, 91% complete.', updatedAt: at(1, 15, 30) },
    { id: sid('mem'), category: 'preferences' as const, key: 'Tone', value: 'Short, direct messages. No fluff.', updatedAt: at(20, 10, 0) },
    { id: sid('mem'), category: 'preferences' as const, key: 'Best contact window', value: '09:00–11:00, Europe/Lisbon.', updatedAt: at(20, 10, 0) },
    { id: sid('mem'), category: 'skills' as const, key: 'Core skills', value: 'Web design, Next.js, SEO, outbound sales, copywriting.', updatedAt: at(30, 10, 0) },
    { id: sid('mem'), category: 'decisions' as const, key: 'Positioning', value: 'Premium websites + AI automation.', updatedAt: at(35, 10, 0) },
    { id: sid('mem'), category: 'decisions' as const, key: 'Pricing', value: '€3,500–€8,000 per project.', updatedAt: at(35, 10, 0) },
    { id: sid('mem'), category: 'context' as const, key: 'Brand', value: 'Building a personal brand around AI automation.', updatedAt: at(12, 10, 0) },
  ];

  const integrations = [
    {
      id: 'google-calendar',
      name: 'Google Calendar',
      provider: 'Google',
      description: 'Read your calendar to protect focus time and schedule execution blocks.',
      icon: Calendar,
      connected: false,
      scopes: ['calendar.read', 'calendar.events'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'gmail',
      name: 'Gmail',
      provider: 'Google',
      description: 'Send approved outreach and follow-ups on your behalf.',
      icon: Mail,
      connected: false,
      scopes: ['gmail.send', 'gmail.read'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'google-drive',
      name: 'Google Drive',
      provider: 'Google',
      description: 'Store briefings, reports and campaign assets.',
      icon: HardDrive,
      connected: false,
      scopes: ['drive.file'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'github',
      name: 'GitHub',
      provider: 'GitHub',
      description: 'Track commits, PRs and repository state for every project.',
      icon: Github,
      connected: false,
      scopes: ['repo', 'read:user'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'vercel',
      name: 'Vercel',
      provider: 'Vercel',
      description: 'Deploy ORBITA and WEAF, and manage environment variables.',
      icon: Triangle,
      connected: false,
      scopes: ['deployments', 'env', 'projects'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'slack',
      name: 'Slack',
      provider: 'Slack',
      description: 'Post briefings and agent updates where your team sees them.',
      icon: Slack,
      connected: false,
      scopes: ['chat:write', 'channels:read'],
      adapterStatus: 'ready' as const,
    },
    {
      id: 'whatsapp',
      name: 'WhatsApp',
      provider: 'Meta',
      description: 'Send approved messages to prospects from your own number.',
      icon: MessageCircle,
      connected: false,
      scopes: ['messages.send'],
      adapterStatus: 'beta' as const,
    },
    {
      id: 'stripe',
      name: 'Stripe',
      provider: 'Stripe',
      description: 'Measure real revenue against your goals. Read-only by default.',
      icon: CreditCard,
      connected: false,
      scopes: ['balance.read', 'charges.read'],
      adapterStatus: 'ready' as const,
    },
  ];

  return {
    user: {
      id: 'u-chelton',
      name: 'Chelton',
      email: 'chelton@atlas.run',
      timezone: 'Europe/Lisbon',
      currency: 'EUR',
      role: 'Founder',
    },
    preferences: {
      defaultPermissionLevel: 2,
      briefingEnabled: true,
      briefingTime: '08:00',
      weekStartsOn: 1,
      currency: 'EUR',
    },
    goals,
    projects,
    agents,
    runs,
    approvals,
    activities,
    insights,
    opportunities,
    memories,
    integrations,
    toasts: [],
    hydrated: false,
  } as AtlasState;
}
